// <auto-generated />
using System;
using AISEP.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AISEP.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260328073442_AddCompletedSessionsToAdvisor")]
    partial class AddCompletedSessionsToAdvisor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AISEP.Domain.Entities.Advisor", b =>
                {
                    b.Property<int>("AdvisorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdvisorID"));

                    b.Property<float?>("AverageRating")
                        .HasColumnType("real");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<int>("CompletedSessions")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DomainTags")
                        .HasColumnType("text");

                    b.Property<string>("ExperiencesJson")
                        .HasColumnType("text");

                    b.Property<string>("Expertise")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("HourlyRate")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkedInURL")
                        .HasColumnType("text");

                    b.Property<string>("MentorshipPhilosophy")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePhotoURL")
                        .HasColumnType("text");

                    b.Property<short>("ProfileStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<string>("Skills")
                        .HasColumnType("text");

                    b.Property<string>("SuitableFor")
                        .HasColumnType("text");

                    b.Property<string>("SupportedDurations")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("TotalMentees")
                        .HasColumnType("integer");

                    b.Property<float>("TotalSessionHours")
                        .HasColumnType("real");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("integer");

                    b.HasKey("AdvisorID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Advisors");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.AdvisorAvailability", b =>
                {
                    b.Property<int>("AvailabilityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AvailabilityID"));

                    b.Property<int>("AdvisorID")
                        .HasColumnType("integer");

                    b.Property<bool>("CalendarConnected")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAcceptingNewMentees")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxConcurrentMentees")
                        .HasColumnType("integer");

                    b.Property<string>("ResponseTimeCommitment")
                        .HasColumnType("text");

                    b.Property<string>("SessionFormats")
                        .HasColumnType("text");

                    b.Property<int?>("TypicalSessionDuration")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("WeeklyAvailableHours")
                        .HasColumnType("integer");

                    b.HasKey("AvailabilityID");

                    b.HasIndex("AdvisorID")
                        .IsUnique();

                    b.ToTable("AdvisorAvailabilities");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.AdvisorIndustryFocus", b =>
                {
                    b.Property<int>("IndustryFocusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IndustryFocusID"));

                    b.Property<int>("AdvisorID")
                        .HasColumnType("integer");

                    b.Property<int>("IndustryID")
                        .HasColumnType("integer");

                    b.HasKey("IndustryFocusID");

                    b.HasIndex("AdvisorID");

                    b.HasIndex("IndustryID");

                    b.ToTable("AdvisorIndustryFocuses");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.AdvisorTestimonial", b =>
                {
                    b.Property<int>("TestimonialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TestimonialID"));

                    b.Property<int>("AdvisorID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsApprovedByFounder")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<int?>("MentorshipID")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int?>("StartupID")
                        .HasColumnType("integer");

                    b.Property<string>("TestimonialText")
                        .HasColumnType("text");

                    b.HasKey("TestimonialID");

                    b.HasIndex("AdvisorID");

                    b.HasIndex("MentorshipID");

                    b.HasIndex("StartupID");

                    b.ToTable("AdvisorTestimonials");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogID"));

                    b.Property<string>("ActionDetails")
                        .HasColumnType("text");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EntityID")
                        .HasColumnType("integer");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("LogID");

                    b.HasIndex("UserID");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.Conversation", b =>
                {
                    b.Property<int>("ConversationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConversationID"));

                    b.Property<int?>("ConnectionID")
                        .HasColumnType("integer");

                    b.Property<short>("ConversationStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MentorshipID")
                        .HasColumnType("integer");

                    b.HasKey("ConversationID");

                    b.HasIndex("ConnectionID");

                    b.HasIndex("MentorshipID");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.Document", b =>
                {
                    b.Property<int>("DocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DocumentID"));

                    b.Property<short>("AnalysisStatus")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("DocumentType")
                        .HasColumnType("smallint");

                    b.Property<string>("FileURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAnalyzed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<int>("StartupID")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("DocumentID");

                    b.HasIndex("StartupID");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.DocumentBlockchainProof", b =>
                {
                    b.Property<int>("ProofID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProofID"));

                    b.Property<DateTime?>("AnchoredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AnchoredBy")
                        .HasColumnType("integer");

                    b.Property<int?>("AnchoredByUserUserID")
                        .HasColumnType("integer");

                    b.Property<string>("BlockNumber")
                        .HasColumnType("text");

                    b.Property<string>("BlockchainNetwork")
                        .HasColumnType("text");

                    b.Property<int>("DocumentID")
                        .HasColumnType("integer");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashAlgorithm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("ProofStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<string>("TransactionHash")
                        .HasColumnType("text");

                    b.HasKey("ProofID");

                    b.HasIndex("AnchoredByUserUserID");

                    b.HasIndex("DocumentID")
                        .IsUnique();

                    b.ToTable("DocumentBlockchainProofs");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.EmailOtp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Otp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EmailOtps");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.FlaggedContent", b =>
                {
                    b.Property<int>("FlagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FlagID"));

                    b.Property<int>("ContentID")
                        .HasColumnType("integer");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FlagDetails")
                        .HasColumnType("text");

                    b.Property<string>("FlagReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FlagSource")
                        .HasColumnType("text");

                    b.Property<DateTime>("FlaggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("ModerationStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<string>("ModeratorNotes")
                        .HasColumnType("text");

                    b.Property<int?>("RelatedUserID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Severity")
                        .HasColumnType("text");

                    b.HasKey("FlagID");

                    b.HasIndex("RelatedUserID");

                    b.HasIndex("ReviewedBy");

                    b.ToTable("FlaggedContents");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.Industry", b =>
                {
                    b.Property<int>("IndustryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IndustryID"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IndustryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentIndustryID")
                        .HasColumnType("integer");

                    b.HasKey("IndustryID");

                    b.HasIndex("ParentIndustryID");

                    b.ToTable("Industries");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.IndustryTrend", b =>
                {
                    b.Property<int>("TrendID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TrendID"));

                    b.Property<string>("AIGeneratedInsights")
                        .HasColumnType("text");

                    b.Property<float?>("AveragePotentialScore")
                        .HasColumnType("real");

                    b.Property<decimal?>("AverageRoundSize")
                        .HasColumnType("numeric");

                    b.Property<string>("CommonWeaknesses")
                        .HasColumnType("text");

                    b.Property<int>("IndustryID")
                        .HasColumnType("integer");

                    b.Property<int>("StartupCount")
                        .HasColumnType("integer");

                    b.Property<string>("TopStrengths")
                        .HasColumnType("text");

                    b.Property<decimal?>("TotalFundingRaised")
                        .HasColumnType("numeric");

                    b.Property<string>("TrendPeriod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TrendID");

                    b.HasIndex("IndustryID");

                    b.ToTable("IndustryTrends");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.InformationRequest", b =>
                {
                    b.Property<int>("RequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestID"));

                    b.Property<int>("ConnectionID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FulfilledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InvestorID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReminderSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestMessage")
                        .HasColumnType("text");

                    b.Property<short>("RequestStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResponseDocumentIDs")
                        .HasColumnType("text");

                    b.Property<string>("ResponseMessage")
                        .HasColumnType("text");

                    b.HasKey("RequestID");

                    b.HasIndex("ConnectionID");

                    b.HasIndex("InvestorID");

                    b.ToTable("InformationRequests");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.Investor", b =>
                {
                    b.Property<int>("InvestorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InvestorID"));

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirmName")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InvestmentThesis")
                        .HasColumnType("text");

                    b.Property<string>("LinkedInURL")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePhotoURL")
                        .HasColumnType("text");

                    b.Property<short>("ProfileStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("InvestorID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Investors");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.InvestorIndustryFocus", b =>
                {
                    b.Property<int>("FocusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FocusID"));

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InvestorID")
                        .HasColumnType("integer");

                    b.HasKey("FocusID");

                    b.HasIndex("InvestorID");

                    b.ToTable("InvestorIndustryFocuses");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.InvestorPreferences", b =>
                {
                    b.Property<int>("PreferenceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PreferenceID"));

                    b.Property<int>("InvestorID")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MaxInvestmentSize")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MinInvestmentSize")
                        .HasColumnType("numeric");

                    b.Property<float?>("MinPotentialScore")
                        .HasColumnType("real");

                    b.Property<string>("PreferredGeographies")
                        .HasColumnType("text");

                    b.Property<string>("PreferredIndustries")
                        .HasColumnType("text");

                    b.Property<string>("PreferredStages")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PreferenceID");

                    b.HasIndex("InvestorID")
                        .IsUnique();

                    b.ToTable("InvestorPreferences");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.InvestorStageFocus", b =>
                {
                    b.Property<int>("StageFocusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StageFocusID"));

                    b.Property<int>("InvestorID")
                        .HasColumnType("integer");

                    b.Property<short>("Stage")
                        .HasColumnType("smallint");

                    b.HasKey("StageFocusID");

                    b.HasIndex("InvestorID");

                    b.ToTable("InvestorStageFocuses");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.InvestorWatchlist", b =>
                {
                    b.Property<int>("WatchlistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WatchlistID"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InvestorID")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastNotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValueSql("1");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StartupID")
                        .HasColumnType("integer");

                    b.Property<string>("WatchReason")
                        .HasColumnType("text");

                    b.HasKey("WatchlistID");

                    b.HasIndex("InvestorID");

                    b.HasIndex("StartupID");

                    b.ToTable("InvestorWatchlists");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.MentorshipFeedback", b =>
                {
                    b.Property<int>("FeedbackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FeedbackID"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<string>("FromRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<int>("MentorshipID")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int?>("SessionID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FeedbackID");

                    b.HasIndex("MentorshipID");

                    b.HasIndex("SessionID");

                    b.ToTable("MentorshipFeedbacks");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.MentorshipReport", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReportID"));

                    b.Property<string>("AttachmentsURL")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByAdvisorID")
                        .HasColumnType("integer");

                    b.Property<string>("DetailedFindings")
                        .HasColumnType("text");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean");

                    b.Property<int>("MentorshipID")
                        .HasColumnType("integer");

                    b.Property<string>("Recommendations")
                        .HasColumnType("text");

                    b.Property<string>("ReportSummary")
                        .HasColumnType("text");

                    b.Property<bool>("ReviewedByStaff")
                        .HasColumnType("boolean");

                    b.Property<int?>("SessionID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ReportID");

                    b.HasIndex("MentorshipID");

                    b.HasIndex("SessionID");

                    b.ToTable("MentorshipReports");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.MentorshipSession", b =>
                {
                    b.Property<int>("SessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SessionID"));

                    b.Property<string>("ActionItems")
                        .HasColumnType("text");

                    b.Property<DateTime?>("AdvisorConfirmedConductedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AdvisorInternalNotes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ConductedConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("KeyInsights")
                        .HasColumnType("text");

                    b.Property<string>("MeetingURL")
                        .HasColumnType("text");

                    b.Property<int>("MentorshipID")
                        .HasColumnType("integer");

                    b.Property<string>("NextSteps")
                        .HasColumnType("text");

                    b.Property<string>("RecommendedResources")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ScheduledStartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionFormat")
                        .HasColumnType("text");

                    b.Property<string>("SessionStatus")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartupConfirmedConductedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StartupNotes")
                        .HasColumnType("text");

                    b.Property<string>("TopicsDiscussed")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SessionID");

                    b.HasIndex("MentorshipID");

                    b.ToTable("MentorshipSessions");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.Message", b =>
                {
                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageID"));

                    b.Property<string>("AttachmentURLs")
                        .HasColumnType("text");

                    b.Property<int>("ConversationID")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SenderUserID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MessageID");

                    b.HasIndex("ConversationID");

                    b.HasIndex("SenderUserID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.ModerationAction", b =>
                {
                    b.Property<int>("ActionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ActionID"));

                    b.Property<string>("ActionDetails")
                        .HasColumnType("text");

                    b.Property<DateTime>("ActionTakenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ActionTakenBy")
                        .HasColumnType("integer");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FlagID")
                        .HasColumnType("integer");

                    b.Property<int>("FlaggedContentFlagID")
                        .HasColumnType("integer");

                    b.Property<string>("MessageToUser")
                        .HasColumnType("text");

                    b.Property<int?>("TargetUserID")
                        .HasColumnType("integer");

                    b.HasKey("ActionID");

                    b.HasIndex("ActionTakenBy");

                    b.HasIndex("FlaggedContentFlagID");

                    b.HasIndex("TargetUserID");

                    b.ToTable("ModerationActions");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationID"));

                    b.Property<string>("ActionURL")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSent")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RelatedEntityID")
                        .HasColumnType("integer");

                    b.Property<string>("RelatedEntityType")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("NotificationID");

                    b.HasIndex("UserID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("PasswordResetTokenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PasswordResetTokenID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("PasswordResetTokenID");

                    b.HasIndex("UserID");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("PermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PermissionID"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PermissionID");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.PlatformAnalytics", b =>
                {
                    b.Property<int>("AnalyticID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnalyticID"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<DateTime>("MetricDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("MetricValue")
                        .HasColumnType("real");

                    b.HasKey("AnalyticID");

                    b.ToTable("PlatformAnalytics");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.PortfolioCompany", b =>
                {
                    b.Property<int>("PortfolioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PortfolioID"));

                    b.Property<string>("CompanyLogoURL")
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short?>("CurrentStatus")
                        .HasColumnType("smallint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExitDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("ExitType")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("ExitValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Industry")
                        .HasColumnType("text");

                    b.Property<decimal?>("InvestmentAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("InvestmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("InvestmentStage")
                        .HasColumnType("smallint");

                    b.Property<int>("InvestorID")
                        .HasColumnType("integer");

                    b.HasKey("PortfolioID");

                    b.HasIndex("InvestorID");

                    b.ToTable("PortfolioCompanies");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RefreshTokenID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IPAddress")
                        .HasColumnType("text");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("RefreshTokenID");

                    b.HasIndex("UserID");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("RolePermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RolePermissionID"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PermissionID")
                        .HasColumnType("integer");

                    b.Property<int>("RoleID")
                        .HasColumnType("integer");

                    b.HasKey("RolePermissionID");

                    b.HasIndex("PermissionID");

                    b.HasIndex("RoleID");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.SavedReport", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReportID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("CreatedByUserUserID")
                        .HasColumnType("integer");

                    b.Property<bool>("IsScheduled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastGeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Parameters")
                        .HasColumnType("text");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("ReportType")
                        .HasColumnType("smallint");

                    b.Property<string>("ScheduleFrequency")
                        .HasColumnType("text");

                    b.HasKey("ReportID");

                    b.HasIndex("CreatedByUserUserID");

                    b.ToTable("SavedReports");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.ScoreImprovementRecommendation", b =>
                {
                    b.Property<int>("RecommendationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecommendationID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpectedImpact")
                        .HasColumnType("text");

                    b.Property<int>("PotentialScoreScoreID")
                        .HasColumnType("integer");

                    b.Property<short>("Priority")
                        .HasColumnType("smallint");

                    b.Property<string>("RecommendationText")
                        .HasColumnType("text");

                    b.Property<int>("ScoreID")
                        .HasColumnType("integer");

                    b.HasKey("RecommendationID");

                    b.HasIndex("PotentialScoreScoreID");

                    b.ToTable("ScoreImprovementRecommendations");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.ScoreSubMetric", b =>
                {
                    b.Property<int>("SubMetricID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubMetricID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("MetricScore")
                        .HasColumnType("real");

                    b.Property<string>("MetricValue")
                        .HasColumnType("text");

                    b.Property<int>("PotentialScoreScoreID")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreID")
                        .HasColumnType("integer");

                    b.HasKey("SubMetricID");

                    b.HasIndex("PotentialScoreScoreID");

                    b.ToTable("ScoreSubMetrics");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.ScoringModelConfiguration", b =>
                {
                    b.Property<int>("ConfigID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConfigID"));

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApplicableStage")
                        .HasColumnType("text");

                    b.Property<string>("ChangeNotes")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatedByUserUserID")
                        .HasColumnType("integer");

                    b.Property<float>("FinancialWeight")
                        .HasColumnType("real");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<float>("MarketWeight")
                        .HasColumnType("real");

                    b.Property<float>("ProductWeight")
                        .HasColumnType("real");

                    b.Property<float>("TeamWeight")
                        .HasColumnType("real");

                    b.Property<float>("TractionWeight")
                        .HasColumnType("real");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ConfigID");

                    b.HasIndex("CreatedByUserUserID");

                    b.ToTable("ScoringModelConfigurations");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.Startup", b =>
                {
                    b.Property<int>("StartupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StartupID"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("integer");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CurrentFundingRaised")
                        .HasColumnType("numeric");

                    b.Property<string>("CurrentNeeds")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FoundedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("FundingAmountSought")
                        .HasColumnType("numeric");

                    b.Property<int?>("IndustryID")
                        .HasColumnType("integer");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkedInURL")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("LogoURL")
                        .HasColumnType("text");

                    b.Property<string>("MarketScope")
                        .HasColumnType("text");

                    b.Property<string>("MetricSummary")
                        .HasColumnType("text");

                    b.Property<string>("OneLiner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProblemStatement")
                        .HasColumnType("text");

                    b.Property<string>("ProductStatus")
                        .HasColumnType("text");

                    b.Property<short>("ProfileStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<string>("SolutionSummary")
                        .HasColumnType("text");

                    b.Property<short?>("Stage")
                        .HasColumnType("smallint");

                    b.Property<string>("SubIndustry")
                        .HasColumnType("text");

                    b.Property<int>("TeamSize")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Valuation")
                        .HasColumnType("numeric");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("StartupID");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("IndustryID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Startups");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.StartupAdvisorMentorship", b =>
                {
                    b.Property<int>("MentorshipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MentorshipID"));

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AdvisorID")
                        .HasColumnType("integer");

                    b.Property<string>("ChallengeDescription")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CompletionConfirmedByAdvisor")
                        .HasColumnType("boolean");

                    b.Property<bool>("CompletionConfirmedByStartup")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpectedDuration")
                        .HasColumnType("text");

                    b.Property<string>("ExpectedScope")
                        .HasColumnType("text");

                    b.Property<string>("LastUpdatedByRole")
                        .HasColumnType("text");

                    b.Property<short>("MentorshipStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<string>("ObligationSummary")
                        .HasColumnType("text");

                    b.Property<string>("PreferredFormat")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectedReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SpecificQuestions")
                        .HasColumnType("text");

                    b.Property<int>("StartupID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MentorshipID");

                    b.HasIndex("AdvisorID");

                    b.HasIndex("StartupID");

                    b.ToTable("StartupAdvisorMentorships");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.StartupInvestorConnection", b =>
                {
                    b.Property<int>("ConnectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConnectionID"));

                    b.Property<string>("AttachedDocumentIDs")
                        .HasColumnType("text");

                    b.Property<short>("ConnectionStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<int?>("InitiatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("InvestorID")
                        .HasColumnType("integer");

                    b.Property<float?>("MatchScore")
                        .HasColumnType("real");

                    b.Property<string>("PersonalizedMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StartupID")
                        .HasColumnType("integer");

                    b.HasKey("ConnectionID");

                    b.HasIndex("InvestorID");

                    b.HasIndex("StartupID");

                    b.ToTable("StartupInvestorConnections");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.StartupPotentialScore", b =>
                {
                    b.Property<int>("ScoreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScoreID"));

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ConfigID")
                        .HasColumnType("integer");

                    b.Property<float>("FinancialScore")
                        .HasColumnType("real");

                    b.Property<bool>("IsCurrentScore")
                        .HasColumnType("boolean");

                    b.Property<float>("MarketScore")
                        .HasColumnType("real");

                    b.Property<float>("OverallScore")
                        .HasColumnType("real");

                    b.Property<float>("ProductScore")
                        .HasColumnType("real");

                    b.Property<int?>("ScoringConfigurationConfigID")
                        .HasColumnType("integer");

                    b.Property<int>("StartupID")
                        .HasColumnType("integer");

                    b.Property<float>("TeamScore")
                        .HasColumnType("real");

                    b.Property<float>("TractionScore")
                        .HasColumnType("real");

                    b.HasKey("ScoreID");

                    b.HasIndex("ScoringConfigurationConfigID");

                    b.HasIndex("StartupID");

                    b.ToTable("StartupPotentialScores");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.SystemSettings", b =>
                {
                    b.Property<int>("SettingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SettingID"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SettingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedByUserUserID")
                        .HasColumnType("integer");

                    b.HasKey("SettingID");

                    b.HasIndex("UpdatedByUserUserID");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.TeamMember", b =>
                {
                    b.Property<int>("TeamMemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TeamMemberID"));

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsFounder")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkedInURL")
                        .HasColumnType("text");

                    b.Property<string>("PhotoURL")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<int>("StartupID")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("integer");

                    b.HasKey("TeamMemberID");

                    b.HasIndex("StartupID");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("UserRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserRoleID"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AssignedBy")
                        .HasColumnType("integer");

                    b.Property<int>("RoleID")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("UserRoleID");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.Advisor", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.User", "User")
                        .WithOne("Advisor")
                        .HasForeignKey("AISEP.Domain.Entities.Advisor", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.AdvisorAvailability", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.Advisor", "Advisor")
                        .WithOne("Availability")
                        .HasForeignKey("AISEP.Domain.Entities.AdvisorAvailability", "AdvisorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advisor");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.AdvisorIndustryFocus", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.Advisor", "Advisor")
                        .WithMany("IndustryFocus")
                        .HasForeignKey("AdvisorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AISEP.Domain.Entities.Industry", "Industry")
                        .WithMany("AdvisorIndustries")
                        .HasForeignKey("IndustryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advisor");

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.AdvisorTestimonial", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.Advisor", "Advisor")
                        .WithMany("Testimonials")
                        .HasForeignKey("AdvisorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AISEP.Domain.Entities.StartupAdvisorMentorship", "Mentorship")
                        .WithMany("Testimonials")
                        .HasForeignKey("MentorshipID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AISEP.Domain.Entities.Startup", "Startup")
                        .WithMany("AdvisorTestimonials")
                        .HasForeignKey("StartupID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Advisor");

                    b.Navigation("Mentorship");

                    b.Navigation("Startup");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.StartupInvestorConnection", "Connection")
                        .WithMany("Conversations")
                        .HasForeignKey("ConnectionID");

                    b.HasOne("AISEP.Domain.Entities.StartupAdvisorMentorship", "Mentorship")
                        .WithMany("Conversations")
                        .HasForeignKey("MentorshipID");

                    b.Navigation("Connection");

                    b.Navigation("Mentorship");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.Document", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.Startup", "Startup")
                        .WithMany("Documents")
                        .HasForeignKey("StartupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Startup");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.DocumentBlockchainProof", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.User", "AnchoredByUser")
                        .WithMany()
                        .HasForeignKey("AnchoredByUserUserID");

                    b.HasOne("AISEP.Domain.Entities.Document", "Document")
                        .WithOne("BlockchainProof")
                        .HasForeignKey("AISEP.Domain.Entities.DocumentBlockchainProof", "DocumentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnchoredByUser");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.EmailOtp", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.User", "User")
                        .WithMany("EmailOtps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.FlaggedContent", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.User", "RelatedUser")
                        .WithMany()
                        .HasForeignKey("RelatedUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AISEP.Domain.Entities.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RelatedUser");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.Industry", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.Industry", "ParentIndustry")
                        .WithMany("SubIndustries")
                        .HasForeignKey("ParentIndustryID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentIndustry");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.IndustryTrend", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.Industry", "Industry")
                        .WithMany("Trends")
                        .HasForeignKey("IndustryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.InformationRequest", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.StartupInvestorConnection", "Connection")
                        .WithMany("InformationRequests")
                        .HasForeignKey("ConnectionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AISEP.Domain.Entities.Investor", "Investor")
                        .WithMany("InformationRequests")
                        .HasForeignKey("InvestorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connection");

                    b.Navigation("Investor");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.Investor", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.User", "User")
                        .WithOne("Investor")
                        .HasForeignKey("AISEP.Domain.Entities.Investor", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.InvestorIndustryFocus", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.Investor", "Investor")
                        .WithMany("IndustryFocus")
                        .HasForeignKey("InvestorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investor");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.InvestorPreferences", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.Investor", "Investor")
                        .WithOne("Preferences")
                        .HasForeignKey("AISEP.Domain.Entities.InvestorPreferences", "InvestorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investor");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.InvestorStageFocus", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.Investor", "Investor")
                        .WithMany("StageFocus")
                        .HasForeignKey("InvestorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investor");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.InvestorWatchlist", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.Investor", "Investor")
                        .WithMany("Watchlists")
                        .HasForeignKey("InvestorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AISEP.Domain.Entities.Startup", "Startup")
                        .WithMany("WatchedByInvestors")
                        .HasForeignKey("StartupID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Investor");

                    b.Navigation("Startup");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.MentorshipFeedback", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.StartupAdvisorMentorship", "Mentorship")
                        .WithMany("Feedbacks")
                        .HasForeignKey("MentorshipID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AISEP.Domain.Entities.MentorshipSession", "Session")
                        .WithMany("Feedbacks")
                        .HasForeignKey("SessionID");

                    b.Navigation("Mentorship");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.MentorshipReport", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.StartupAdvisorMentorship", "Mentorship")
                        .WithMany("Reports")
                        .HasForeignKey("MentorshipID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AISEP.Domain.Entities.MentorshipSession", "Session")
                        .WithMany("Reports")
                        .HasForeignKey("SessionID");

                    b.Navigation("Mentorship");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.MentorshipSession", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.StartupAdvisorMentorship", "Mentorship")
                        .WithMany("Sessions")
                        .HasForeignKey("MentorshipID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mentorship");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.Message", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AISEP.Domain.Entities.User", "SenderUser")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.ModerationAction", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.User", "ActionTakenByUser")
                        .WithMany()
                        .HasForeignKey("ActionTakenBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AISEP.Domain.Entities.FlaggedContent", "FlaggedContent")
                        .WithMany("ModerationActions")
                        .HasForeignKey("FlaggedContentFlagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AISEP.Domain.Entities.User", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActionTakenByUser");

                    b.Navigation("FlaggedContent");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.Notification", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.PortfolioCompany", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.Investor", "Investor")
                        .WithMany("PortfolioCompanies")
                        .HasForeignKey("InvestorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investor");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AISEP.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.SavedReport", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.ScoreImprovementRecommendation", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.StartupPotentialScore", "PotentialScore")
                        .WithMany("ImprovementRecommendations")
                        .HasForeignKey("PotentialScoreScoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PotentialScore");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.ScoreSubMetric", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.StartupPotentialScore", "PotentialScore")
                        .WithMany("SubMetrics")
                        .HasForeignKey("PotentialScoreScoreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PotentialScore");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.ScoringModelConfiguration", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserUserID");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.Startup", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AISEP.Domain.Entities.Industry", "Industry")
                        .WithMany()
                        .HasForeignKey("IndustryID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AISEP.Domain.Entities.User", "User")
                        .WithOne("Startup")
                        .HasForeignKey("AISEP.Domain.Entities.Startup", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Industry");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.StartupAdvisorMentorship", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.Advisor", "Advisor")
                        .WithMany("Mentorships")
                        .HasForeignKey("AdvisorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AISEP.Domain.Entities.Startup", "Startup")
                        .WithMany("Mentorships")
                        .HasForeignKey("StartupID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Advisor");

                    b.Navigation("Startup");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.StartupInvestorConnection", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.Investor", "Investor")
                        .WithMany("StartupConnections")
                        .HasForeignKey("InvestorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AISEP.Domain.Entities.Startup", "Startup")
                        .WithMany("InvestorConnections")
                        .HasForeignKey("StartupID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Investor");

                    b.Navigation("Startup");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.StartupPotentialScore", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.ScoringModelConfiguration", "ScoringConfiguration")
                        .WithMany("PotentialScores")
                        .HasForeignKey("ScoringConfigurationConfigID");

                    b.HasOne("AISEP.Domain.Entities.Startup", "Startup")
                        .WithMany("PotentialScores")
                        .HasForeignKey("StartupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScoringConfiguration");

                    b.Navigation("Startup");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.SystemSettings", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserUserID");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.TeamMember", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.Startup", "Startup")
                        .WithMany("TeamMembers")
                        .HasForeignKey("StartupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Startup");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("AISEP.Domain.Entities.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AISEP.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AISEP.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.Advisor", b =>
                {
                    b.Navigation("Availability");

                    b.Navigation("IndustryFocus");

                    b.Navigation("Mentorships");

                    b.Navigation("Testimonials");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.Document", b =>
                {
                    b.Navigation("BlockchainProof");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.FlaggedContent", b =>
                {
                    b.Navigation("ModerationActions");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.Industry", b =>
                {
                    b.Navigation("AdvisorIndustries");

                    b.Navigation("SubIndustries");

                    b.Navigation("Trends");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.Investor", b =>
                {
                    b.Navigation("IndustryFocus");

                    b.Navigation("InformationRequests");

                    b.Navigation("PortfolioCompanies");

                    b.Navigation("Preferences");

                    b.Navigation("StageFocus");

                    b.Navigation("StartupConnections");

                    b.Navigation("Watchlists");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.MentorshipSession", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.ScoringModelConfiguration", b =>
                {
                    b.Navigation("PotentialScores");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.Startup", b =>
                {
                    b.Navigation("AdvisorTestimonials");

                    b.Navigation("Documents");

                    b.Navigation("InvestorConnections");

                    b.Navigation("Mentorships");

                    b.Navigation("PotentialScores");

                    b.Navigation("TeamMembers");

                    b.Navigation("WatchedByInvestors");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.StartupAdvisorMentorship", b =>
                {
                    b.Navigation("Conversations");

                    b.Navigation("Feedbacks");

                    b.Navigation("Reports");

                    b.Navigation("Sessions");

                    b.Navigation("Testimonials");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.StartupInvestorConnection", b =>
                {
                    b.Navigation("Conversations");

                    b.Navigation("InformationRequests");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.StartupPotentialScore", b =>
                {
                    b.Navigation("ImprovementRecommendations");

                    b.Navigation("SubMetrics");
                });

            modelBuilder.Entity("AISEP.Domain.Entities.User", b =>
                {
                    b.Navigation("Advisor");

                    b.Navigation("AuditLogs");

                    b.Navigation("EmailOtps");

                    b.Navigation("Investor");

                    b.Navigation("Notifications");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RefreshTokens");

                    b.Navigation("SentMessages");

                    b.Navigation("Startup");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
