using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AISEP.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddIncidentEntity : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Use raw SQL to handle out-of-sync DB
            // (production DB was partially created manually, table may already exist)
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""Incidents"" (
                    ""IncidentID"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Title"" text NOT NULL,
                    ""Description"" text NOT NULL,
                    ""Severity"" smallint NOT NULL,
                    ""Status"" smallint NOT NULL,
                    ""CreatedBy"" integer NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""ResolvedAt"" timestamp with time zone,
                    ""ResolvedBy"" integer,
                    ""RollbackNotes"" text,
                    ""IsRolledBack"" boolean NOT NULL DEFAULT false,
                    ""CreatedByUserUserID"" integer,
                    ""ResolvedByUserUserID"" integer
                );

                DO $$ BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Incidents_Users_CreatedByUserUserID') THEN
                        ALTER TABLE ""Incidents"" ADD CONSTRAINT ""FK_Incidents_Users_CreatedByUserUserID""
                            FOREIGN KEY (""CreatedByUserUserID"") REFERENCES ""Users""(""UserID"");
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Incidents_Users_ResolvedByUserUserID') THEN
                        ALTER TABLE ""Incidents"" ADD CONSTRAINT ""FK_Incidents_Users_ResolvedByUserUserID""
                            FOREIGN KEY (""ResolvedByUserUserID"") REFERENCES ""Users""(""UserID"");
                    END IF;
                END $$;

                CREATE INDEX IF NOT EXISTS ""IX_Incidents_CreatedByUserUserID""
                    ON ""Incidents"" (""CreatedByUserUserID"");
                CREATE INDEX IF NOT EXISTS ""IX_Incidents_ResolvedByUserUserID""
                    ON ""Incidents"" (""ResolvedByUserUserID"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Incidents");
        }
    }
}
